### ISSUE TITLE
Error when parsing the scannet data by using scannet-export.py

### ISSUE THREAD

**Issue by ZuoJiaxing** [ardaduz/deep-video-mvs#13]
Hi, I get the following error when parsing the scannet data. Do you have any clues for it?

Traceback (most recent call last):
  File "./scannet-export.py", line 300, in <module>
    pool.join()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 474, in join
    assert self._state in (CLOSE, TERMINATE)

**Comment by ZuoJiaxing** [comment]
It is fine and finishes the data parsing.
